name: Build and test

on:
  merge_group:
  pull_request:
  push:
    branches: [main]

jobs:
  build-and-test:
    strategy:
      matrix:
        buildtype: [debug, release]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Update apt repositories for ccache
        run: sudo apt update
      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ccache-linux-${{ matrix.buildtype }}
      - name: Setup compiler and build tools
        run: sudo apt install --no-install-recommends --yes g++-12 meson ninja-build
      - name: Configure
        run: |
            CXX="ccache g++-12" meson setup \
              --buildtype ${{ matrix.buildtype }} \
              --warnlevel 3 \
              --werror \
              build .
      - name: Build
        run: ninja -C build
      - name: Test
        run: ./build/unit
